name: ICIS Data Scraper

on:
  schedule:
    - cron: '0 22 * * *' # 每天 22:00 UTC (香港时间早上6点)
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Chrome via apt-get
        # 这是您参考范例中使用的、经过验证的安装方式
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver

      - name: Install Python dependencies
        run: pip install -r requirements.txt
      
      - name: Create service account key file
        # 确保你在 GitHub Secrets 中的名字是 GCP_SA_KEY
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: echo "$GCP_SA_KEY" > service_account_key.json

      - name: Run Python script
        # 将所有需要的 Secrets 作为环境变量传给脚本
        env:
          ICIS_USERNAME: ${{ secrets.ICIS_USERNAME }}
          ICIS_PASSWORD: ${{ secrets.ICIS_PASSWORD }}
          # 明确设置 chromedriver 的路径，供 Python 脚本使用
          CHROMEDRIVER_PATH: /usr/bin/chromedriver
        run: python main.py

      - name: Upload Debug PDF on Failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: error-page-pdf
          path: webpage_error.pdf
          if-no-files-found: ignore
